let CustomErrorHandler,JwtService;_86d‍.x([["default",()=>_86d‍.o]]);_86d‍.w("../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);_86d‍.w("../services/JwtService",[["default",["JwtService"],function(v){JwtService=v}]]);


const auth = async (req, res, next) => {
  let authHeader = req.headers.authorization
  if (!authHeader) {
    return next(CustomErrorHandler.unAuthorized('No Token in here'))
  }

  const token = authHeader.split(' ')[1]

  try {
    const { _id, name, email } =  JwtService.verify(token)

    const user = {
      _id,
      name,
      email
    }
    req.user = user

    next()
  } catch (error) {
    return next(CustomErrorHandler.unAuthorized('something Went Wrong'))
  }
}

_86d‍.d(auth);
